apiVersion: v1
kind: ConfigMap
metadata:
  name: stackdriver-log-validator
data:
  stackdriver-log-verifier: |
    {
      "templateName": "stackdriver-log-validator",
      "monitoringProvider": "STACKDRIVER",
      "accountName": "stackdriver-demosever",
      "filterKey": "resource.labels.pod_name",
      "tags": [],
      "index": "dummy-index",
      "errorTopics": [
        {
          "string": "OnOutOfMemoryError",
          "topic": "CRITICAL",
          "type": "default"
        }
      ],
      "responseKeywords": "textPayload"
    }
