apiVersion: v1
kind: ConfigMap
metadata:
  name: stackdriver-generic-ext
data:
  stackdriver-generic-ext: |
    monitoringProvider: STACKDRIVER
    accountName: stackdriver-account-name
    filterKey: resource.labels.pod_name
    responseKeywords: textPayload
    errorTopics: 
    - errorString: ArrayIndexOutOfBounds
      topic: ERROR
    - errorString: NullPointerException
      topic: ERROR
    tags:
    - errorString: FATAL
      tag: FatalErrors
