apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-health-validator
data: 
 Template: ISDTemplate
 TemplateType: Metric
 Json: |
  {
    "filterKey": "${namespace_key},${pod_key},${app_name}",
    "data": {
      "percent_diff_threshold": "hard",
      "isNormalize": false,
      "groups": [
        {
          "metrics": [
            {
              "metricType": "ADVANCED",
              "accountName": "prometheus-demoserver",
              "riskDirection": "Higher",
              "customThresholdHigher": 70,
              "name": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace_key}\", pod=~\".*${pod_key}.*\"}[5m]))",
              "customThresholdLower": "10"
            }
          ],
          "group": "CPU Usage By Pod Name"
        },
        {
          "metrics": [
            {
              "metricType": "ADVANCED",
              "accountName": "prometheus-demoserver",
              "riskDirection": "Higher",
              "customThresholdHigher": 70,
              "name": "sum(container_memory_usage_bytes{namespace=\"${namespace_key}\", pod=~\".*${pod_key}.*\"})",
              "customThresholdLower": "10"
            }
          ],
          "group": "Memory Usage By Pod Name"
        },
        {
          "metrics": [
            {
              "metricType": "ADVANCED",
              "accountName": "prometheus-demoserver",
              "riskDirection": "Higher",
              "customThresholdHigher": 90,
              "name": "sum(rate(http_server_requests_seconds_sum{app=\"${app_name}\",kubernetes_pod_name=~\"${pod_key}\"}[5m])) / sum(rate(http_server_requests_seconds_count{app=\"${app_name}\",kubernetes_pod_name=~\"${pod_key}\"}[5m]))",
              "customThresholdLower": "10"
            }
          ],
          "group": "Application Latency"
        },
        {
          "metrics": [
            {
              "metricType": "ADVANCED",
              "accountName": "prometheus-demoserver",
              "riskDirection": "Lower",
              "customThresholdHigher": 50,
              "name": "avg(rate(http_server_requests_seconds_count{app=\"${app_name}\",kubernetes_pod_name=~\"${pod_key}\"}[5m]))",
              "customThresholdLower": 90
            }
          ],
          "group": "Application Request Rate"
        },
        {
          "metrics": [
            {
              "metricType": "ADVANCED",
              "accountName": "prometheus-demoserver",
              "riskDirection": "Higher",
              "customThresholdHigher": 70,
              "name": "sum(rate(http_server_requests_seconds_count{app=\"${app_name}\",kubernetes_pod_name=~\"${pod_key}\",status=~\"^[45]..$\"}[5m])) / sum(rate(http_server_requests_seconds_count{app=\"${app_name}\",kubernetes_pod_name=~\"${pod_key}\"}[5m]))",
              "customThresholdLower": "10"
            }
          ],
          "group": "Application Error Rate"
        }
      ]
    },
    "templateName": "prometheus-health-validator",
    "isEdit": false,
    "advancedProvider": "PROMETHEUS"
  }
