apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-log-validator
data:
  elasticsearch-log-validator: |
    {
     "templateName": "elasticsearch-log-validator",
     "monitoringProvider": "ELASTICSEARCH",
     "accountName": "elastic-demoserver",
     "index": "kubernetes*",
     "filterKey": "kubernetes.pod_name",
     "tags": [
     {
       "string": "outOfmemory",
       "tag": "Customtag",
       "id": ""
     }
       ],
     "errorTopics": [
     {
       "string": "WARNING",
       "topic": "WARN",
       "type": "default"
     }
     ],
     "responseKeywords": "log"
     }
